# -*- coding: utf-8 -*-
from odoo import fields, models

class ProductCategory(models.Model):
    _inherit = "product.category"

    categ_public_id = fields.Many2one(
        'product.public.category', string='e-Commerce Category'
    )
    cat_code = fields.Char('Cat Code')
    category_name = fields.Selection(
        [
            ('electric_acc', 'ELECTRIC ACC'),
            ('battery', 'BATTERY'),
            ('telephone_accessories', 'TELEPHONE ACCESSORIES'),
            ('food_preparation', 'FOOD PREPARATION'),
            ('torch', 'TORCH'),
            ('miscellaneous_office', 'MISCELLANEOUS_OFFICE'),
            ('electric_pan_cooker', 'ELECTRIC PAN & COOKER'),
            ('electric_jarpot', 'ELECTRIC JARPOT'),
            ('stove', 'STOVE'),
            ('adhesive', 'ADHESIVE'),
            ('adult', 'ADULT'),
            ('air_condition_accessoriess', 'AIR CONDITION ACCESSORIESS'),
            ('air_fresheners', 'AIR FRESHENERS'),
            ('antiseptics_cleansing', 'ANTISEPTICS-CLEANSING'),
            ('baby_cradle', 'BABY CRADLE'),
            ('baby_walker', 'BABY WALKER'),
            ('baby_body_moisturizer', 'BABY_BODY MOISTURIZER'),
            ('baby_milk_powder', 'BABY_MILK POWDER'),
            ('back_pack', 'BACK PACK'),
            ('baking_desserts', 'BAKING & DESSERTS'),
            ('bar', 'BAR'),
            ('bar_soap_body_care', 'BAR SOAP_BODY CARE'),
            ('bar_soap_body_cleanse', 'BAR SOAP_BODY CLEANSE'),
            ('bar_stick', 'BAR/STICK'),
            ('basic_care', 'BASIC CARE'),
            ('bath_accessoriess', 'BATH ACCESSORIESS'),
            ('bath_equipment', 'BATH EQUIPMENT'),
            ('bathroom_accessoriess', 'BATHROOM ACCESSORIESS'),
            ('bathroom_cleane', 'BATHROOM CLEANE'),
            ('bed_mattress', 'BED & MATTRESS'),
            ('bed_set', 'BED SET'),
            ('bedding', 'BEDDING'),
            ('bedding_equipment', 'BEDDING EQUIPMENT'),
            ('bedsheet', 'BEDSHEET'),
            ('beef_other', 'BEEF & OTHER'),
            ('belt_suspender', 'BELT/SUSPENDER'),
            ('beverage_utensils', 'BEVERAGE UTENSILS'),
            ('beverges', 'BEVERGES'),
            ('biscuits', 'BISCUITS'),
            ('body_cologne', 'BODY COLOGNE'),
            ('body_lotion', 'BODY LOTION'),
            ('bottles_nipples', 'BOTTLES & NIPPLES'),
            ('boys_toys', 'BOYS TOYS'),
            ('bra_lingeries', 'BRA_LINGERIES'),
            ('bread', 'BREAD'),
            ('bread_spreads', 'BREAD SPREADS'),
            ('brush', 'BRUSH'),
            ('brush_bottle_sterilization', 'BRUSH & BOTTLE STERILIZATION'),
            ('buddhist_products', 'BUDDHIST PRODUCTS'),
            ('bugs_killer', 'BUGS KILLER'),
            ('building_hardware_work_shop _equip_protect_acc', 'BUILDING HARDWARE/WORK SHOP  EQUIP &PROTECT ACC.'),
            ('business_bag', 'BUSINESS BAG'),
            ('cabinet', 'CABINET'),
            ('cake', 'CAKE'),
            ('cakes_pies', 'CAKES/PIES'),
            ('camisoles_slips', 'CAMISOLES & SLIPS'),
            ('camping', 'CAMPING'),
            ('candy', 'CANDY'),
            ('canned_food', 'CANNED FOOD'),
            ('canned_milk_hot_drink', 'CANNED MILK HOT DRINK'),
            ('canned_jar_vege', 'CANNED/JAR VEGE'),
            ('carpet', 'CARPET'),
            ('casual_men_shoes', 'CASUAL MEN SHOES'),
            ('cat_food', 'CAT FOOD'),
            ('ceramic_porcelain_opalware', 'CERAMIC/PORCELAIN/OPALWARE'),
            ('chair_stool', 'CHAIR & STOOL'),
            ('cheese_spread', 'CHEESE & SPREAD'),
            ('chest_rubs_inhalants', 'CHEST RUBS & INHALANTS'),
            ('chew_candy', 'CHEW CANDY'),
            ('chicken_frozen_butchery', 'CHICKEN_FROZEN BUTCHERY'),
            ('child_saf_equip', 'CHILD SAF EQUIP'),
            ('chips', 'CHIPS'),
            ('chocolate_candy', 'CHOCOLATE CANDY'),
            ('cleaning_acc', 'CLEANING ACC.'),
            ('cleaning_equip', 'CLEANING EQUIP.'),
            ('cleansing_sheet', 'CLEANSING SHEET'),
            ('cloth_drier_cloth_line', 'CLOTH DRIER/CLOTH LINE'),
            ('coffee', 'COFFEE'),
            ('cold_cereal', 'COLD CEREAL'),
            ('cold_cut', 'COLD CUT'),
            ('cond_treatment', 'COND.&TREATMENT'),
            ('condom', 'CONDOM'),
            ('cooking_oil', 'COOKING OIL'),
            ('cooking_sauces', 'COOKING SAUCES'),
            ('cooking_utinsils', 'COOKING UTINSILS'),
            ('correction', 'CORRECTION'),
            ('cosmetic_accessoriess', 'COSMETIC ACCESSORIESS'),
            ('cost', 'COST'),
            ('cotton', 'COTTON'),
            ('crab_frozen_seafood', 'CRAB_FROZEN SEAFOOD'),
            ('crackers', 'CRACKERS'),
        ], 'Category Name'
    )
    sub_cat_code = fields.Char('Sub Cat Code')
    sub_category_name = fields.Char('Sub Category Name')
