# -*- coding: utf-8 -*-
{
    'name': "lod_rental_space",
    'sequence': -100,
    'summary' : '',
    'description' : """""",
    'author': "Lay & Xaiykham",
    'website' : 'https://www.laoodoo.com',
    'category': 'Rental Space',
    'version': '18.0.1.0.0',
    'depends': ['mail','product','base', 'account','sale', 'lo_sale_enhancement', 'purchase_requisition'],
    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/sequence_data.xml',
        'reports/report.xml',
        'reports/report_quotation_rental.xml', 
        # 'reports/report_sale_order_rental.xml',
        'reports/report_contract_rental.xml',
        'reports/report_invoice_account_rental.xml',
        # 'reports/report_rental_space_template.xml',
        # 'reports/rental_space_status_report_template.xml',
        'wizard/create_customer_view.xml',
        # 'wizard/report_rental_space_view.xml',
        # 'wizard/rental_space_status_wizard_views.xml',
        # wizard
        'views/rental_space_quotations.xml',
        'views/rental_space_view.xml',
        'views/agreement_view.xml', 
        'views/config_tag_view.xml',
        'views/invoice_view.xml',
        'views/rental_space_type_view.xml',
        # 'views/product_view.xml',
        "views/agreement_terms_template_views.xml",
        "views/rental_partner_view.xml",
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}